apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ../base/external-secrets
- https://github.com/redhat-appstudio/image-controller/config/default?ref=6ae4f0b83851bd9aeef9a4cb2f4d3ef6775ed674

namespace: image-controller

images:
- name: quay.io/redhat-appstudio/image-controller
  newName: quay.io/redhat-appstudio/image-controller
  newTag: 6ae4f0b83851bd9aeef9a4cb2f4d3ef6775ed674

patches:
  - path: ./manager_resources_patch.yaml
  - path: quaytoken.yaml
    target:
      name: quaytoken
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
  